version: 2
project_name: exo-credential-helper
dist: dist-exo-credential-helper
builds:
  - id: exo-credential-helper
    dir: ./go/exo-credential-helper
    main: .
    binary: exo-credential-helper
    env:
      - CGO_ENABLED=0
    tags:
      - exohubapi
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.appVersion={{ .Version }}
archives:
  - id: exo-credential-helper
    builds: [exo-credential-helper]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
release:
  skip_upload: true
