package bundle

import (
	"archive/zip"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestParseChunkSize(t *testing.T) {
	tests := []struct {
		input    string
		expected int64
	}{
		{"1GiB", 1024 * 1024 * 1024},
		{"1GB", 1000 * 1000 * 1000},
		{"500MiB", 500 * 1024 * 1024},
		{"100MB", 100 * 1000 * 1000},
		{"1KiB", 1024},
		{"1KB", 1000},
		{"1024", 1024},
		{"", 0},
		{"invalid", 0},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := parseChunkSize(tt.input)
			if got != tt.expected {
				t.Errorf("parseChunkSize(%q) = %d, want %d", tt.input, got, tt.expected)
			}
		})
	}
}

func TestDeriveChunks(t *testing.T) {
	key := "SHA256E-s2684354560--abc123def456.parquet"
	fileSize := int64(2684354560)  // ~2.5 GiB
	chunkSize := int64(1073741824) // 1 GiB
	s3URL := "s3://bucket/prefix"

	chunks := deriveChunks(key, fileSize, chunkSize, s3URL)

	if len(chunks) != 3 {
		t.Fatalf("expected 3 chunks, got %d", len(chunks))
	}

	// Chunk 1
	if chunks[0].ChunkNumber != 1 {
		t.Errorf("chunk 1 number = %d, want 1", chunks[0].ChunkNumber)
	}
	if chunks[0].ChunkSize != chunkSize {
		t.Errorf("chunk 1 size = %d, want %d", chunks[0].ChunkSize, chunkSize)
	}
	expectedKey1 := "SHA256E-s2684354560-S1073741824-C1--abc123def456.parquet"
	if chunks[0].ChunkKey != expectedKey1 {
		t.Errorf("chunk 1 key = %q, want %q", chunks[0].ChunkKey, expectedKey1)
	}
	if chunks[0].S3Path != s3URL+"/"+expectedKey1 {
		t.Errorf("chunk 1 s3path = %q, want %q", chunks[0].S3Path, s3URL+"/"+expectedKey1)
	}

	// Chunk 3 (last, partial)
	if chunks[2].ChunkNumber != 3 {
		t.Errorf("chunk 3 number = %d, want 3", chunks[2].ChunkNumber)
	}
	expectedLastSize := fileSize - 2*chunkSize
	if chunks[2].ChunkSize != expectedLastSize {
		t.Errorf("chunk 3 size = %d, want %d", chunks[2].ChunkSize, expectedLastSize)
	}
}

func TestDeriveChunksNoSplit(t *testing.T) {
	key := "SHA256E-s100--abc.dat"
	// Key without -- separator should return nil
	chunks := deriveChunks("NODASH", 100, 50, "s3://b")
	if chunks != nil {
		t.Errorf("expected nil chunks for key without --, got %v", chunks)
	}

	// File smaller than chunk size: no chunks should be generated by caller,
	// but deriveChunks still produces 1 chunk if called
	chunks = deriveChunks(key, 50, 100, "s3://b")
	if len(chunks) != 1 {
		t.Errorf("expected 1 chunk for small file, got %d", len(chunks))
	}
}

func TestExtractRemoteName(t *testing.T) {
	tests := []struct {
		desc     string
		expected string
	}{
		{"00000000-0000-0000-0000-000000000001 -- s3-annex [origin]", "s3-annex"},
		{"00000000-0000-0000-0000-000000000002 -- s3-export", "s3-export"},
		{"my-remote", "my-remote"},
		{"  spaced  ", "spaced"},
		{"[s3-annex]", "s3-annex"},
		{"[s3-export]", "s3-export"},
		{"00000000-0000-0000-0000-000000000003 -- [s3-annex]", "s3-annex"},
	}

	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			got := extractRemoteName(tt.desc)
			if got != tt.expected {
				t.Errorf("extractRemoteName(%q) = %q, want %q", tt.desc, got, tt.expected)
			}
		})
	}
}

func TestMatchesFilters(t *testing.T) {
	tests := []struct {
		name   string
		path   string
		preset Preset
		want   bool
	}{
		{
			name:   "no filters matches all",
			path:   "any/path/file.txt",
			preset: Preset{},
			want:   true,
		},
		{
			name:   "include matches",
			path:   "data/file.parquet",
			preset: Preset{Include: []string{"**/*.parquet"}},
			want:   true,
		},
		{
			name:   "include does not match",
			path:   "data/file.csv",
			preset: Preset{Include: []string{"**/*.parquet"}},
			want:   false,
		},
		{
			name:   "exclude matches",
			path:   "data/temp.tmp",
			preset: Preset{Exclude: []string{"*.tmp"}},
			want:   false,
		},
		{
			name:   "exclude does not match",
			path:   "data/file.csv",
			preset: Preset{Exclude: []string{"*.tmp"}},
			want:   true,
		},
		{
			name:   "include then exclude",
			path:   "data/temp.parquet",
			preset: Preset{Include: []string{"**/*.parquet"}, Exclude: []string{"**/temp.*"}},
			want:   false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := matchesFilters(tt.path, tt.preset)
			if got != tt.want {
				t.Errorf("matchesFilters(%q, %+v) = %v, want %v", tt.path, tt.preset, got, tt.want)
			}
		})
	}
}

func TestGlobMatch(t *testing.T) {
	tests := []struct {
		pattern string
		path    string
		want    bool
	}{
		{"**/*.parquet", "data/file.parquet", true},
		{"**/*.parquet", "a/b/c/file.parquet", true},
		{"**/*.parquet", "file.parquet", true},
		{"**/*.parquet", "file.csv", false},
		{"*.tmp", "file.tmp", true},
		{"*.tmp", "dir/file.tmp", true}, // matches basename
		{"data/**", "data/file.txt", true},
		{"data/**", "other/file.txt", false},
	}

	for _, tt := range tests {
		t.Run(tt.pattern+"_"+tt.path, func(t *testing.T) {
			got := globMatch(tt.pattern, tt.path)
			if got != tt.want {
				t.Errorf("globMatch(%q, %q) = %v, want %v", tt.pattern, tt.path, got, tt.want)
			}
		})
	}
}

func TestLoadPresetDefault(t *testing.T) {
	// When no .exohub/bundle exists, default preset should be returned
	dir := t.TempDir()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	preset, err := loadPreset("default")
	if err != nil {
		t.Fatalf("loadPreset(default) error: %v", err)
	}
	if preset.Name != "default" {
		t.Errorf("preset.Name = %q, want %q", preset.Name, "default")
	}
	if preset.Scope != "all" {
		t.Errorf("preset.Scope = %q, want %q", preset.Scope, "all")
	}
}

func TestLoadPresetFromFile(t *testing.T) {
	dir := t.TempDir()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	os.MkdirAll(".exohub", 0755)
	content := `presets:
  - name: default
    scope: all
  - name: parquet-only
    scope: annex
    include:
      - "**/*.parquet"
`
	os.WriteFile(filepath.Join(".exohub", "bundle"), []byte(content), 0644)

	// Load default
	preset, err := loadPreset("default")
	if err != nil {
		t.Fatalf("loadPreset(default) error: %v", err)
	}
	if preset.Scope != "all" {
		t.Errorf("default scope = %q, want %q", preset.Scope, "all")
	}

	// Load named preset
	preset, err = loadPreset("parquet-only")
	if err != nil {
		t.Fatalf("loadPreset(parquet-only) error: %v", err)
	}
	if preset.Scope != "annex" {
		t.Errorf("parquet-only scope = %q, want %q", preset.Scope, "annex")
	}
	if len(preset.Include) != 1 || preset.Include[0] != "**/*.parquet" {
		t.Errorf("parquet-only include = %v, want [**/*.parquet]", preset.Include)
	}

	// Unknown preset
	_, err = loadPreset("nonexistent")
	if err == nil {
		t.Fatal("expected error for nonexistent preset")
	}
}

func TestLoadPresetIncrementalField(t *testing.T) {
	dir := t.TempDir()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	os.MkdirAll(".exohub", 0755)
	content := `presets:
  - name: default
    scope: all
    incremental: true
  - name: no-incremental
    scope: all
`
	os.WriteFile(filepath.Join(".exohub", "bundle"), []byte(content), 0644)

	// Preset with incremental: true should parse correctly
	preset, err := loadPreset("default")
	if err != nil {
		t.Fatalf("loadPreset(default) error: %v", err)
	}
	if !preset.Incremental {
		t.Errorf("expected preset.Incremental = true, got false")
	}

	// Preset without incremental field should default to false
	preset, err = loadPreset("no-incremental")
	if err != nil {
		t.Fatalf("loadPreset(no-incremental) error: %v", err)
	}
	if preset.Incremental {
		t.Errorf("expected preset.Incremental = false, got true")
	}

	// CLI flag false + preset true => incremental should be true (OR logic)
	incremental := false || preset.Incremental
	if incremental {
		t.Errorf("expected merged incremental = false when both are false")
	}

	preset, _ = loadPreset("default")
	incremental = false || preset.Incremental
	if !incremental {
		t.Errorf("expected merged incremental = true when preset.Incremental = true and CLI flag = false")
	}

	// CLI flag true overrides everything
	incremental = true || preset.Incremental
	if !incremental {
		t.Errorf("expected merged incremental = true when CLI flag = true")
	}
}

func TestExpandCommits(t *testing.T) {
	commitMap := map[string]Commit{
		"aaa": {Hash: "aaa", Subject: "first", CommitterDate: "2024-01-01T00:00:00Z"},
		"bbb": {Hash: "bbb", Subject: "second", CommitterDate: "2024-01-02T00:00:00Z"},
		"ccc": {Hash: "ccc", Subject: "third", CommitterDate: "2024-01-03T00:00:00Z"},
	}

	// Normal expansion
	result := expandCommits([]string{"bbb", "aaa"}, commitMap)
	if len(result) != 2 {
		t.Fatalf("expected 2 commits, got %d", len(result))
	}
	// Should be sorted by date descending
	if result[0].Hash != "bbb" {
		t.Errorf("first commit should be bbb (most recent), got %s", result[0].Hash)
	}

	// Deduplication
	result = expandCommits([]string{"aaa", "aaa", "aaa"}, commitMap)
	if len(result) != 1 {
		t.Errorf("expected 1 commit after dedup, got %d", len(result))
	}

	// Empty hashes
	result = expandCommits(nil, commitMap)
	if len(result) != 0 {
		t.Errorf("expected 0 commits for nil input, got %d", len(result))
	}

	// Hash not in map
	result = expandCommits([]string{"zzz"}, commitMap)
	if len(result) != 0 {
		t.Errorf("expected 0 commits for unknown hash, got %d", len(result))
	}
}

func TestIsHex(t *testing.T) {
	if !isHex("abc123def456") {
		t.Error("expected abc123def456 to be hex")
	}
	if !isHex("ABC123") {
		t.Error("expected ABC123 to be hex")
	}
	if isHex("xyz") {
		t.Error("expected xyz to not be hex")
	}
	if isHex("") {
		t.Error("expected empty string to not be hex")
	}
}

func TestBuildLocations(t *testing.T) {
	remoteConfigs := map[string]RemoteConfig{
		"s3-annex": {
			Name:  "s3-annex",
			Type:  "annex",
			S3URL: "s3://bucket/prefix",
			Chunk: "1GiB",
		},
		"s3-export": {
			Name:  "s3-export",
			Type:  "export",
			S3URL: "s3://bucket/export",
		},
	}

	whereis := annexWhereisEntry{
		File: "data/file.parquet",
		Key:  "SHA256E-s100--abc123.parquet",
		Whereis: []annexWhereisRemote{
			{UUID: "uuid-1", Description: "uuid-1 -- s3-annex [origin]", Here: false},
			{UUID: "uuid-local", Description: "uuid-local -- here", Here: true},
			{UUID: "uuid-2", Description: "uuid-2 -- s3-export", Here: false},
		},
	}

	locations := buildLocations("data/file.parquet", "SHA256E-s100--abc123.parquet", 100, whereis, remoteConfigs)

	// Should have 2 locations (local excluded)
	if len(locations) != 2 {
		t.Fatalf("expected 2 locations, got %d", len(locations))
	}

	// Annex remote
	if locations[0].Remote != "s3-annex" {
		t.Errorf("location 0 remote = %q, want s3-annex", locations[0].Remote)
	}
	if locations[0].Type != "annex" {
		t.Errorf("location 0 type = %q, want annex", locations[0].Type)
	}
	// Small file (100 bytes < 1GiB) with chunking enabled: git-annex still uses chunk key format
	if locations[0].S3Object != "" {
		t.Errorf("chunked file should have empty s3_object, got %q", locations[0].S3Object)
	}
	if len(locations[0].Chunks) != 1 {
		t.Fatalf("expected 1 chunk for small file with chunking enabled, got %d", len(locations[0].Chunks))
	}
	expectedChunkKey := "SHA256E-s100-S1073741824-C1--abc123.parquet"
	if locations[0].Chunks[0].ChunkKey != expectedChunkKey {
		t.Errorf("chunk key = %q, want %q", locations[0].Chunks[0].ChunkKey, expectedChunkKey)
	}
	if locations[0].Chunks[0].ChunkSize != 100 {
		t.Errorf("chunk size = %d, want 100", locations[0].Chunks[0].ChunkSize)
	}

	// Export remote
	if locations[1].Remote != "s3-export" {
		t.Errorf("location 1 remote = %q, want s3-export", locations[1].Remote)
	}
	if locations[1].ExportPath != "s3://bucket/export/data/file.parquet" {
		t.Errorf("location 1 export_path = %q", locations[1].ExportPath)
	}
}

func TestBuildLocationsChunked(t *testing.T) {
	remoteConfigs := map[string]RemoteConfig{
		"s3-annex": {
			Name:  "s3-annex",
			Type:  "annex",
			S3URL: "s3://bucket/prefix",
			Chunk: "1GiB",
		},
	}

	fileSize := int64(2684354560) // ~2.5 GiB
	whereis := annexWhereisEntry{
		Whereis: []annexWhereisRemote{
			{UUID: "uuid-1", Description: "uuid-1 -- s3-annex", Here: false},
		},
	}

	locations := buildLocations("big.dat", "SHA256E-s2684354560--abc123.dat", fileSize, whereis, remoteConfigs)

	if len(locations) != 1 {
		t.Fatalf("expected 1 location, got %d", len(locations))
	}

	// Chunked: s3_object should be empty, chunks should be populated
	if locations[0].S3Object != "" {
		t.Errorf("chunked file should have empty s3_object, got %q", locations[0].S3Object)
	}
	if len(locations[0].Chunks) != 3 {
		t.Fatalf("expected 3 chunks, got %d", len(locations[0].Chunks))
	}
}

func TestBuildLocationsUntrusted(t *testing.T) {
	remoteConfigs := map[string]RemoteConfig{
		"old-remote": {
			Name:  "old-remote",
			Type:  "annex",
			S3URL: "s3://old",
		},
	}

	whereis := annexWhereisEntry{
		Untrusted: []annexWhereisRemote{
			{UUID: "uuid-old", Description: "uuid-old -- old-remote", Here: false},
		},
	}

	locations := buildLocations("f.txt", "SHA256E-s10--abc.txt", 10, whereis, remoteConfigs)

	if len(locations) != 1 {
		t.Fatalf("expected 1 location, got %d", len(locations))
	}
	if !locations[0].Untrusted {
		t.Error("expected untrusted=true for untrusted remote")
	}
}

func TestBuildLocationsSkipsUnconfiguredRemotes(t *testing.T) {
	remoteConfigs := map[string]RemoteConfig{
		"s3-annex": {
			Name:  "s3-annex",
			Type:  "annex",
			S3URL: "s3://bucket/prefix",
		},
	}

	whereis := annexWhereisEntry{
		Whereis: []annexWhereisRemote{
			// Replica/clone - not in remoteConfigs, should be skipped
			{UUID: "uuid-replica", Description: "user@host:/path/to/repo", Here: false},
			// Configured remote with brackets
			{UUID: "uuid-annex", Description: "[s3-annex]", Here: false},
		},
	}

	locations := buildLocations("f.txt", "SHA256E-s10--abc.txt", 10, whereis, remoteConfigs)

	if len(locations) != 1 {
		t.Fatalf("expected 1 location (replica skipped), got %d", len(locations))
	}
	if locations[0].Remote != "s3-annex" {
		t.Errorf("location remote = %q, want s3-annex", locations[0].Remote)
	}
	if locations[0].Type != "annex" {
		t.Errorf("location type = %q, want annex", locations[0].Type)
	}
}

func TestIsExohubPath(t *testing.T) {
	tests := []struct {
		path string
		want bool
	}{
		{".exohub/bundle", true},
		{".exohub/remotes", true},
		{".exohub", true},
		{"data/.exohub/file", false},
		{"exohub/file", false},
		{"data/file.txt", false},
	}
	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			if got := isExohubPath(tt.path); got != tt.want {
				t.Errorf("isExohubPath(%q) = %v, want %v", tt.path, got, tt.want)
			}
		})
	}
}

func TestIsArtifactDBPath(t *testing.T) {
	tests := []struct {
		path string
		want bool
	}{
		{".artifactdb/metadata.json", true},
		{".artifactdb", true},
		{".artifactdb/sub/file.json", true},
		{"data/.artifactdb/file", false},
		{"artifactdb/file", false},
		{"data/file.txt", false},
	}
	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			if got := isArtifactDBPath(tt.path); got != tt.want {
				t.Errorf("isArtifactDBPath(%q) = %v, want %v", tt.path, got, tt.want)
			}
		})
	}
}

func TestIsHiddenPath(t *testing.T) {
	tests := []struct {
		path string
		want bool
	}{
		{".github/workflows/ci.yml", true},
		{".gitattributes", true},
		{"data/.hidden/file.txt", true},
		{".dvc/config", true},
		{"data/file.txt", false},
		{"src/main.go", false},
		{"a/b/c/file", false},
	}
	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			if got := isHiddenPath(tt.path); got != tt.want {
				t.Errorf("isHiddenPath(%q) = %v, want %v", tt.path, got, tt.want)
			}
		})
	}
}

func TestShouldSkipPath(t *testing.T) {
	tests := []struct {
		name       string
		path       string
		preset     Preset
		wantSkip   bool
		wantReason bool // whether a non-empty reason is expected
	}{
		{
			name:     "normal file not skipped",
			path:     "data/file.parquet",
			preset:   Preset{},
			wantSkip: false,
		},
		{
			name:     "exohub always skipped",
			path:     ".exohub/bundle",
			preset:   Preset{IncludeHidden: true},
			wantSkip: true,
		},
		{
			name:       "artifactdb skipped by default",
			path:       ".artifactdb/metadata.json",
			preset:     Preset{},
			wantSkip:   true,
			wantReason: true,
		},
		{
			name:       "artifactdb skipped even with include_hidden",
			path:       ".artifactdb/index.json",
			preset:     Preset{IncludeHidden: true},
			wantSkip:   true,
			wantReason: true,
		},
		{
			name:     "artifactdb included via explicit include pattern",
			path:     ".artifactdb/metadata.json",
			preset:   Preset{Include: []string{".artifactdb/**"}},
			wantSkip: false,
		},
		{
			name:     "hidden path skipped by default",
			path:     ".github/workflows/ci.yml",
			preset:   Preset{},
			wantSkip: true,
		},
		{
			name:     "hidden path included with include_hidden",
			path:     ".github/workflows/ci.yml",
			preset:   Preset{IncludeHidden: true},
			wantSkip: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			skip, reason := shouldSkipPath(tt.path, tt.preset)
			if skip != tt.wantSkip {
				t.Errorf("shouldSkipPath(%q) skip = %v, want %v", tt.path, skip, tt.wantSkip)
			}
			if tt.wantReason && reason == "" {
				t.Errorf("shouldSkipPath(%q) expected non-empty reason", tt.path)
			}
			if !tt.wantReason && reason != "" {
				t.Errorf("shouldSkipPath(%q) unexpected reason: %s", tt.path, reason)
			}
		})
	}
}

func TestGenerateCommitArtifacts(t *testing.T) {
	dir := t.TempDir()
	commitsDir := filepath.Join(dir, "commits")

	commits := []Commit{
		{
			Hash:           "aaaa1111bbbb2222cccc3333dddd4444eeee5555",
			Parents:        []string{"0000111122223333444455556666777788889999"},
			AuthorName:     "Alice",
			AuthorEmail:    "alice@example.com",
			AuthorDate:     "2024-01-15T10:00:00+00:00",
			CommitterName:  "Alice",
			CommitterEmail: "alice@example.com",
			CommitterDate:  "2024-01-15T10:00:00+00:00",
			Subject:        "add data files",
			Body:           "",
		},
		{
			Hash:           "ffff6666aaaa7777bbbb8888cccc9999dddd0000",
			Parents:        []string{"aaaa1111bbbb2222cccc3333dddd4444eeee5555"},
			AuthorName:     "Bob",
			AuthorEmail:    "bob@example.com",
			AuthorDate:     "2024-01-16T12:00:00+00:00",
			CommitterName:  "Bob",
			CommitterEmail: "bob@example.com",
			CommitterDate:  "2024-01-16T12:00:00+00:00",
			Subject:        "update README",
			Body:           "More details here.",
		},
	}

	commitFiles := map[string][]string{
		"aaaa1111bbbb2222cccc3333dddd4444eeee5555": {"data/file1.parquet", "data/file2.parquet"},
		"ffff6666aaaa7777bbbb8888cccc9999dddd0000": {"README.md"},
	}

	// Mark data files as annexed
	annexedFiles := map[string]bool{
		"data/file1.parquet": true,
		"data/file2.parquet": true,
	}

	count, err := generateCommitArtifacts(commitsDir, "headhash123", "https://example.com/repo.git", commits, commitFiles, annexedFiles)
	if err != nil {
		t.Fatalf("generateCommitArtifacts error: %v", err)
	}
	if count != 2 {
		t.Fatalf("expected 2 commit artifacts, got %d", count)
	}

	// Verify first commit JSON
	data, err := os.ReadFile(filepath.Join(commitsDir, "aaaa1111bbbb2222cccc3333dddd4444eeee5555.json"))
	if err != nil {
		t.Fatalf("ReadFile error: %v", err)
	}
	var ca CommitArtifact
	if err := json.Unmarshal(data, &ca); err != nil {
		t.Fatalf("Unmarshal error: %v", err)
	}
	if ca.Schema != "exohub-commit/v1.json" {
		t.Errorf("schema = %q, want exohub-commit/v1.json", ca.Schema)
	}
	if ca.Hash != "aaaa1111bbbb2222cccc3333dddd4444eeee5555" {
		t.Errorf("hash mismatch")
	}
	if len(ca.AnnexFiles) != 2 {
		t.Errorf("expected 2 annex_files, got %d", len(ca.AnnexFiles))
	}
	if len(ca.GitFiles) != 0 {
		t.Errorf("expected 0 git_files, got %d", len(ca.GitFiles))
	}
	if ca.RepoURL != "https://example.com/repo.git" {
		t.Errorf("repo_url = %q", ca.RepoURL)
	}
	if ca.Ref != "headhash123" {
		t.Errorf("ref = %q", ca.Ref)
	}

	// Verify second commit — README.md is git-only
	data2, err := os.ReadFile(filepath.Join(commitsDir, "ffff6666aaaa7777bbbb8888cccc9999dddd0000.json"))
	if err != nil {
		t.Fatalf("ReadFile error: %v", err)
	}
	var ca2 CommitArtifact
	if err := json.Unmarshal(data2, &ca2); err != nil {
		t.Fatalf("Unmarshal error: %v", err)
	}
	if len(ca2.GitFiles) != 1 || ca2.GitFiles[0] != "README.md" {
		t.Errorf("expected git_files=[README.md], got %v", ca2.GitFiles)
	}
	if len(ca2.AnnexFiles) != 0 {
		t.Errorf("expected 0 annex_files, got %d", len(ca2.AnnexFiles))
	}
}

func TestGenerateCommitArtifactsEmptyFiles(t *testing.T) {
	dir := t.TempDir()
	commitsDir := filepath.Join(dir, "commits")

	commits := []Commit{
		{
			Hash:    "aaaa1111bbbb2222cccc3333dddd4444eeee5555",
			Subject: "empty commit",
		},
	}

	// No files for this commit
	commitFiles := map[string][]string{}

	count, err := generateCommitArtifacts(commitsDir, "head", "url", commits, commitFiles, map[string]bool{})
	if err != nil {
		t.Fatalf("error: %v", err)
	}
	if count != 1 {
		t.Fatalf("expected 1, got %d", count)
	}

	data, err := os.ReadFile(filepath.Join(commitsDir, "aaaa1111bbbb2222cccc3333dddd4444eeee5555.json"))
	if err != nil {
		t.Fatalf("ReadFile error: %v", err)
	}
	var ca CommitArtifact
	if err := json.Unmarshal(data, &ca); err != nil {
		t.Fatalf("Unmarshal error: %v", err)
	}
	// annex_files and git_files should be empty arrays, not null
	if ca.AnnexFiles == nil {
		t.Errorf("annex_files should be empty array, not nil")
	}
	if len(ca.AnnexFiles) != 0 {
		t.Errorf("expected 0 annex_files, got %d", len(ca.AnnexFiles))
	}
	if ca.GitFiles == nil {
		t.Errorf("git_files should be empty array, not nil")
	}
	if len(ca.GitFiles) != 0 {
		t.Errorf("expected 0 git_files, got %d", len(ca.GitFiles))
	}
}

func TestBundleInfoSerialization(t *testing.T) {
	info := BundleInfo{
		Schema:            "exohub-bundle/v1.json",
		RepoURL:           "https://example.com/repo.git",
		Ref:               "abc123",
		RefName:           "v1.0.0",
		RefType:           "tag",
		FromRef:           "v0.9.0",
		GeneratedAt:       "2024-01-15T10:00:00Z",
		Preset:            "default",
		Scope:             "all",
		CommitCount:       35,
		FileCount:         150,
		AnnexFileCount:    120,
		GitFileCount:      30,
		MarkdownFileCount: 5,
		TotalSize:         1073741824,
		ExoVersion:        "0.46.0",
	}

	data, err := json.Marshal(info)
	if err != nil {
		t.Fatalf("Marshal error: %v", err)
	}

	var parsed BundleInfo
	if err := json.Unmarshal(data, &parsed); err != nil {
		t.Fatalf("Unmarshal error: %v", err)
	}

	if parsed.Schema != "exohub-bundle/v1.json" {
		t.Errorf("schema = %q", parsed.Schema)
	}
	if parsed.RefType != "tag" {
		t.Errorf("ref_type = %q", parsed.RefType)
	}
	if parsed.CommitCount != 35 {
		t.Errorf("commit_count = %d", parsed.CommitCount)
	}
	if parsed.FileCount != 150 {
		t.Errorf("file_count = %d", parsed.FileCount)
	}
	if parsed.AnnexFileCount != 120 {
		t.Errorf("annex_file_count = %d", parsed.AnnexFileCount)
	}
	if parsed.GitFileCount != 30 {
		t.Errorf("git_file_count = %d", parsed.GitFileCount)
	}
	if parsed.TotalSize != 1073741824 {
		t.Errorf("total_size = %d", parsed.TotalSize)
	}
	if parsed.RepoURL != "https://example.com/repo.git" {
		t.Errorf("repo_url = %q", parsed.RepoURL)
	}
	if parsed.MarkdownFileCount != 5 {
		t.Errorf("markdown_file_count = %d", parsed.MarkdownFileCount)
	}
}

func TestWriteJSON(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "sub", "dir", "test.json")

	data := map[string]string{"key": "value"}
	err := writeJSON(path, data)
	if err != nil {
		t.Fatalf("writeJSON error: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile error: %v", err)
	}

	expected := "{\n  \"key\": \"value\"\n}\n"
	if string(content) != expected {
		t.Errorf("writeJSON content = %q, want %q", string(content), expected)
	}
}

func TestMaybeCreateArtipacks_BelowThreshold(t *testing.T) {
	dir := t.TempDir()

	// Create 5 files (below default threshold of 1000)
	for i := 0; i < 5; i++ {
		os.WriteFile(filepath.Join(dir, fmt.Sprintf("file%d.json", i)), []byte("{}"), 0644)
	}

	if err := maybeCreateArtipacks(dir); err != nil {
		t.Fatalf("maybeCreateArtipacks failed: %v", err)
	}

	// No artipack should be created
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), artipackExtension) {
			t.Errorf("unexpected artipack created: %s", e.Name())
		}
	}
}

func TestMaybeCreateArtipacks_AboveThreshold(t *testing.T) {
	dir := t.TempDir()

	// Use a low threshold via env var
	t.Setenv("ARTIFACTDB_ZIP_THRESHOLD", "10")

	// Create 15 files (above threshold of 10)
	for i := 0; i < 15; i++ {
		os.WriteFile(filepath.Join(dir, fmt.Sprintf("file%d.json", i)), []byte(`{"id":`+fmt.Sprintf("%d", i)+`}`), 0644)
	}

	if err := maybeCreateArtipacks(dir); err != nil {
		t.Fatalf("maybeCreateArtipacks failed: %v", err)
	}

	// Should have exactly one artipack
	entries, _ := os.ReadDir(dir)
	var artipacks []string
	var others []string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), artipackExtension) {
			artipacks = append(artipacks, e.Name())
		} else {
			others = append(others, e.Name())
		}
	}

	if len(artipacks) != 1 {
		t.Fatalf("expected 1 artipack, got %d: %v", len(artipacks), artipacks)
	}
	if len(others) != 0 {
		t.Errorf("expected original files to be deleted, got %d remaining: %v", len(others), others)
	}

	// Verify archive contents
	reader, err := zip.OpenReader(filepath.Join(dir, artipacks[0]))
	if err != nil {
		t.Fatalf("failed to open artipack: %v", err)
	}
	defer reader.Close()

	if len(reader.File) != 15 {
		t.Errorf("artipack contains %d files, want 15", len(reader.File))
	}
}

func TestMaybeCreateArtipacks_Disabled(t *testing.T) {
	dir := t.TempDir()

	t.Setenv("ARTIFACTDB_ZIP_ENABLED", "false")
	t.Setenv("ARTIFACTDB_ZIP_THRESHOLD", "1")

	// Create 5 files (above threshold but disabled)
	for i := 0; i < 5; i++ {
		os.WriteFile(filepath.Join(dir, fmt.Sprintf("file%d.json", i)), []byte("{}"), 0644)
	}

	if err := maybeCreateArtipacks(dir); err != nil {
		t.Fatalf("maybeCreateArtipacks failed: %v", err)
	}

	// No artipack should be created
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), artipackExtension) {
			t.Errorf("unexpected artipack created when disabled: %s", e.Name())
		}
	}
}

func TestMaybeCreateArtipacks_MultipleArchives(t *testing.T) {
	dir := t.TempDir()

	t.Setenv("ARTIFACTDB_ZIP_THRESHOLD", "5")
	t.Setenv("ARTIFACTDB_ZIP_MAX_FILES", "10")

	// Create 25 files → should produce 3 artipacks (10+10+5)
	for i := 0; i < 25; i++ {
		os.WriteFile(filepath.Join(dir, fmt.Sprintf("f%03d.json", i)), []byte("{}"), 0644)
	}

	if err := maybeCreateArtipacks(dir); err != nil {
		t.Fatalf("maybeCreateArtipacks failed: %v", err)
	}

	entries, _ := os.ReadDir(dir)
	var artipacks []string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), artipackExtension) {
			artipacks = append(artipacks, e.Name())
		}
	}

	if len(artipacks) != 3 {
		t.Fatalf("expected 3 artipacks, got %d: %v", len(artipacks), artipacks)
	}
}

func TestBuildBlobInfoMap(t *testing.T) {
	// Create a temporary git repo with known files
	dir := t.TempDir()

	run := func(args ...string) {
		t.Helper()
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "HOME="+dir)
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("command %v failed: %v\n%s", args, err, out)
		}
	}

	run("git", "init")
	run("git", "config", "user.email", "test@test.com")
	run("git", "config", "user.name", "Test")

	// Create files with known content
	os.WriteFile(filepath.Join(dir, "hello.txt"), []byte("hello world\n"), 0o644)
	os.MkdirAll(filepath.Join(dir, "sub"), 0o755)
	os.WriteFile(filepath.Join(dir, "sub", "data.csv"), []byte("a,b,c\n1,2,3\n"), 0o644)

	run("git", "add", ".")
	run("git", "commit", "-m", "init")

	// Change to the temp repo dir so buildBlobInfoMap uses it
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	m, err := buildBlobInfoMap(nil)
	if err != nil {
		t.Fatalf("buildBlobInfoMap(nil) error: %v", err)
	}

	// Verify both files are present
	if _, ok := m["hello.txt"]; !ok {
		t.Error("missing hello.txt in blob info map")
	}
	if _, ok := m["sub/data.csv"]; !ok {
		t.Error("missing sub/data.csv in blob info map")
	}

	// Verify sizes match file content lengths
	if m["hello.txt"].Size != 12 {
		t.Errorf("hello.txt size = %d, want 12", m["hello.txt"].Size)
	}
	if m["sub/data.csv"].Size != 12 {
		t.Errorf("sub/data.csv size = %d, want 12", m["sub/data.csv"].Size)
	}

	// Verify hashes are non-empty
	if m["hello.txt"].Hash == "" {
		t.Error("hello.txt hash is empty")
	}
	if m["sub/data.csv"].Hash == "" {
		t.Error("sub/data.csv hash is empty")
	}
}

func TestParseAnnexKey(t *testing.T) {
	tests := []struct {
		key     string
		backend string
		size    int64
	}{
		{"SHA256E-s28592304514--0becad2e7602bb8aea9aebdf1e9d27d34408dd97f845261fdd5a19f2f32695dd.tdb", "SHA256E", 28592304514},
		{"SHA256E-s12345--abc123.parquet", "SHA256E", 12345},
		{"MD5E-s100--deadbeef.txt", "MD5E", 100},
		{"WORM-s0--abc", "WORM", 0},
		{"SHA256E-s1073741824--hash.ext", "SHA256E", 1073741824},
		{"SHA256", "SHA256", 0},               // no dash, no size
		{"", "", 0},                           // empty key
		{"URL--http://example.com", "URL", 0}, // URL backend, no size
	}

	for _, tt := range tests {
		t.Run(tt.key, func(t *testing.T) {
			backend, size := parseAnnexKey(tt.key)
			if backend != tt.backend {
				t.Errorf("parseAnnexKey(%q) backend = %q, want %q", tt.key, backend, tt.backend)
			}
			if size != tt.size {
				t.Errorf("parseAnnexKey(%q) size = %d, want %d", tt.key, size, tt.size)
			}
		})
	}
}

func TestCleanAnnexMetadataFields(t *testing.T) {
	fields := map[string]interface{}{
		"role":             "builder",
		"tag":              []interface{}{"exp1", "exp2"},
		"count":            float64(2),
		"lastchanged":      "2026-04-17@23-00-00",
		"role-lastchanged": "2026-04-17@23-00-00",
	}

	got := cleanAnnexMetadataFields(fields)

	want := map[string][]string{
		"role":  {"builder"},
		"tag":   {"exp1", "exp2"},
		"count": {"2"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("cleanAnnexMetadataFields() = %#v, want %#v", got, want)
	}
}

func TestParseAnnexMetadataOutputIndexesByKeyAndFile(t *testing.T) {
	keyOnly := `{"fields":{"lastchanged":["2026-04-17@23-00-00"],"role":["builder"],"role-lastchanged":["2026-04-17@23-00-00"]},"key":"K1"}`
	withFile := `{"file":"seekers/lelongs/profile_80s_8bit.png","fields":{"tag":["experiment1"]},"key":"K2"}`

	got := parseAnnexMetadataOutput([]byte(keyOnly + "\n" + withFile + "\n"))

	if _, ok := got.ByFile["K1"]; ok {
		t.Fatalf("unexpected file index for key-only entry")
	}

	role := got.ByKey["K1"]["role"]
	if !reflect.DeepEqual(role, []string{"builder"}) {
		t.Fatalf("ByKey[K1][role] = %#v, want %#v", role, []string{"builder"})
	}

	tag := got.ByFile["seekers/lelongs/profile_80s_8bit.png"]["tag"]
	if !reflect.DeepEqual(tag, []string{"experiment1"}) {
		t.Fatalf("ByFile[path][tag] = %#v, want %#v", tag, []string{"experiment1"})
	}
}

func TestDisplayFromRef(t *testing.T) {
	if got := displayFromRef(""); got != "(all commits)" {
		t.Errorf("displayFromRef(\"\") = %q, want \"(all commits)\"", got)
	}
	if got := displayFromRef("abc123"); got != "abc123" {
		t.Errorf("displayFromRef(\"abc123\") = %q, want \"abc123\"", got)
	}
}

func TestLoadRemoteConfigs(t *testing.T) {
	dir := t.TempDir()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	// No .exohub/remotes — should return nil, nil
	m, err := loadRemoteConfigs()
	if err != nil {
		t.Fatalf("expected nil error for missing file, got %v", err)
	}
	if m != nil {
		t.Fatalf("expected nil map for missing file, got %v", m)
	}

	// Create .exohub/remotes
	os.MkdirAll(filepath.Join(dir, ".exohub"), 0o755)
	remotes := `remotes:
  - name: s5-annex
    type: annex
    uuid: 1da2bc67-8f81-48c6-8a59-8752f482e688
    s3url: s3://bucket/prefix
    chunk: 1GiB
  - name: s5-export
    type: export
    uuid: 5b758405-e8c6-4673-a4eb-2487438e155e
    s3url: s3://bucket/export
`
	os.WriteFile(filepath.Join(dir, ".exohub", "remotes"), []byte(remotes), 0o644)

	m, err = loadRemoteConfigs()
	if err != nil {
		t.Fatalf("loadRemoteConfigs error: %v", err)
	}
	if len(m) != 2 {
		t.Fatalf("expected 2 remotes, got %d", len(m))
	}
	if m["s5-annex"].UUID != "1da2bc67-8f81-48c6-8a59-8752f482e688" {
		t.Errorf("s5-annex UUID = %q", m["s5-annex"].UUID)
	}
	if m["s5-annex"].Chunk != "1GiB" {
		t.Errorf("s5-annex Chunk = %q", m["s5-annex"].Chunk)
	}
	if m["s5-export"].Type != "export" {
		t.Errorf("s5-export Type = %q", m["s5-export"].Type)
	}
}

func TestLoadRemoteConfigsInvalidYAML(t *testing.T) {
	dir := t.TempDir()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	os.MkdirAll(filepath.Join(dir, ".exohub"), 0o755)
	os.WriteFile(filepath.Join(dir, ".exohub", "remotes"), []byte("not: [valid: yaml"), 0o644)

	_, err := loadRemoteConfigs()
	if err == nil {
		t.Error("expected error for invalid YAML")
	}
}

func TestBuildLocationsUUIDMatching(t *testing.T) {
	remoteConfigs := map[string]RemoteConfig{
		"delta-data": {
			Name: "delta-data",
			Type: "exospace",
			UUID: "afb6e679-92a3-4e1c-b01b-06f52d5ecb2e",
		},
		"s5-annex": {
			Name:  "s5-annex",
			Type:  "annex",
			UUID:  "1da2bc67-8f81-48c6-8a59-8752f482e688",
			S3URL: "s3://bucket/annex/",
			Chunk: "1GiB",
		},
	}

	whereis := annexWhereisEntry{
		File: "data/file.parquet",
		Key:  "SHA256E-s12345--abc.parquet",
		Whereis: []annexWhereisRemote{
			// UUID matches delta-data but description doesn't parse to "delta-data"
			{UUID: "afb6e679-92a3-4e1c-b01b-06f52d5ecb2e", Description: "exospace-metadata [delta-data]", Here: false},
			// UUID matches s5-annex
			{UUID: "1da2bc67-8f81-48c6-8a59-8752f482e688", Description: "[s5-annex]", Here: false},
			// Local remote — should be skipped
			{UUID: "local-uuid", Description: "here", Here: true},
			// Unknown remote — should be skipped
			{UUID: "unknown-uuid", Description: "some-clone", Here: false},
		},
	}

	locations := buildLocations("data/file.parquet", "SHA256E-s12345--abc.parquet", 12345, whereis, remoteConfigs)

	if len(locations) != 2 {
		t.Fatalf("expected 2 locations, got %d", len(locations))
	}

	// Check delta-data matched by UUID
	var foundDelta, foundS5 bool
	for _, loc := range locations {
		switch loc.Remote {
		case "delta-data":
			foundDelta = true
			if loc.UUID != "afb6e679-92a3-4e1c-b01b-06f52d5ecb2e" {
				t.Errorf("delta-data UUID = %q", loc.UUID)
			}
			if loc.Type != "exospace" {
				t.Errorf("delta-data Type = %q", loc.Type)
			}
		case "s5-annex":
			foundS5 = true
			if loc.Type != "annex" {
				t.Errorf("s5-annex Type = %q", loc.Type)
			}
		}
	}
	if !foundDelta {
		t.Error("delta-data not found in locations (UUID matching failed)")
	}
	if !foundS5 {
		t.Error("s5-annex not found in locations")
	}
}

func TestBuildLocationsTrailingSlash(t *testing.T) {
	remoteConfigs := map[string]RemoteConfig{
		"s5-annex": {
			Name:  "s5-annex",
			Type:  "annex",
			UUID:  "uuid-123",
			S3URL: "s3://bucket/prefix/",
		},
	}
	whereis := annexWhereisEntry{
		Whereis: []annexWhereisRemote{
			{UUID: "uuid-123", Description: "[s5-annex]", Here: false},
		},
	}

	locations := buildLocations("file.txt", "SHA256E-s100--abc.txt", 100, whereis, remoteConfigs)
	if len(locations) != 1 {
		t.Fatalf("expected 1 location, got %d", len(locations))
	}

	// S3URL should have trailing slash stripped
	if locations[0].S3URL != "s3://bucket/prefix" {
		t.Errorf("S3URL = %q, want no trailing slash", locations[0].S3URL)
	}
	// S3Object should not have double slash
	if locations[0].S3Object != "s3://bucket/prefix/SHA256E-s100--abc.txt" {
		t.Errorf("S3Object = %q, want single slash", locations[0].S3Object)
	}
}

func TestBuildLocationsChunkedTrailingSlash(t *testing.T) {
	remoteConfigs := map[string]RemoteConfig{
		"s5-annex": {
			Name:  "s5-annex",
			Type:  "annex",
			UUID:  "uuid-123",
			S3URL: "s3://bucket/prefix/",
			Chunk: "1GiB",
		},
	}
	whereis := annexWhereisEntry{
		Whereis: []annexWhereisRemote{
			{UUID: "uuid-123", Description: "[s5-annex]", Here: false},
		},
	}

	// File larger than chunk size
	locations := buildLocations("big.parquet", "SHA256E-s2684354560--abc.parquet", 2684354560, whereis, remoteConfigs)
	if len(locations) != 1 {
		t.Fatalf("expected 1 location, got %d", len(locations))
	}
	if len(locations[0].Chunks) == 0 {
		t.Fatal("expected chunks for large file")
	}
	// Chunk S3Path should not have double slash (after the s3:// scheme)
	for _, chunk := range locations[0].Chunks {
		pathPart := strings.TrimPrefix(chunk.S3Path, "s3://")
		if strings.Contains(pathPart, "//") {
			t.Errorf("chunk S3Path has double slash: %s", chunk.S3Path)
		}
	}
}

func TestBuildLocationsExportType(t *testing.T) {
	remoteConfigs := map[string]RemoteConfig{
		"s5-export": {
			Name:  "s5-export",
			Type:  "export",
			UUID:  "uuid-456",
			S3URL: "s3://bucket/export/",
		},
	}
	whereis := annexWhereisEntry{
		Whereis: []annexWhereisRemote{
			{UUID: "uuid-456", Description: "[s5-export]", Here: false},
		},
	}

	locations := buildLocations("data/file.parquet", "SHA256E-s100--abc.parquet", 100, whereis, remoteConfigs)
	if len(locations) != 1 {
		t.Fatalf("expected 1 location, got %d", len(locations))
	}
	if locations[0].ExportPath != "s3://bucket/export/data/file.parquet" {
		t.Errorf("ExportPath = %q, want no double slash", locations[0].ExportPath)
	}
}

func TestBuildLocationsEmpty(t *testing.T) {
	remoteConfigs := map[string]RemoteConfig{
		"s5-annex": {Name: "s5-annex", UUID: "uuid-123"},
	}
	// whereis with no remotes
	whereis := annexWhereisEntry{}
	locations := buildLocations("file.txt", "key", 0, whereis, remoteConfigs)
	if len(locations) != 0 {
		t.Errorf("expected 0 locations for empty whereis, got %d", len(locations))
	}
}

func TestBuildLocationsNameFallback(t *testing.T) {
	remoteConfigs := map[string]RemoteConfig{
		"s5-annex": {
			Name:  "s5-annex",
			Type:  "annex",
			UUID:  "", // no UUID — must match by name
			S3URL: "s3://bucket/prefix",
		},
	}
	whereis := annexWhereisEntry{
		Whereis: []annexWhereisRemote{
			{UUID: "some-uuid", Description: "[s5-annex]", Here: false},
		},
	}

	locations := buildLocations("file.txt", "SHA256E-s100--abc.txt", 100, whereis, remoteConfigs)
	if len(locations) != 1 {
		t.Fatalf("expected 1 location via name fallback, got %d", len(locations))
	}
	if locations[0].Remote != "s5-annex" {
		t.Errorf("Remote = %q, want s5-annex", locations[0].Remote)
	}
}

func TestGenerateGitArtifactsBasic(t *testing.T) {
	dir := t.TempDir()

	run := func(args ...string) {
		t.Helper()
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "HOME="+dir)
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("command %v failed: %v\n%s", args, err, out)
		}
	}

	run("git", "init")
	run("git", "config", "user.email", "test@test.com")
	run("git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(dir, "README.md"), []byte("# Hello\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "src.go"), []byte("package main\n"), 0o644)
	run("git", "add", ".")
	run("git", "commit", "-m", "init")

	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	filesDir := filepath.Join(dir, "output", "files")
	blobInfoMap, err := buildBlobInfoMap(nil)
	if err != nil {
		t.Fatalf("buildBlobInfoMap error: %v", err)
	}

	pathCommits := map[string][]string{
		"README.md": {"aaaa"},
		"src.go":    {"aaaa"},
	}
	commitMap := map[string]Commit{
		"aaaa": {Hash: "aaaa", Subject: "init"},
	}

	count, totalSize, err := generateGitArtifacts(filesDir, "headhash", "https://example.com/repo.git", Preset{}, pathCommits, commitMap, blobInfoMap, false, nil, false, map[string]bool{}, map[string]bool{}, nil)
	if err != nil {
		t.Fatalf("generateGitArtifacts error: %v", err)
	}
	if count != 2 {
		t.Errorf("expected 2 artifacts, got %d", count)
	}
	if totalSize == 0 {
		t.Error("expected non-zero totalSize")
	}

	// Verify artifact JSON
	data, err := os.ReadFile(filepath.Join(filesDir, "README.md.json"))
	if err != nil {
		t.Fatalf("ReadFile error: %v", err)
	}
	var artifact Artifact
	if err := json.Unmarshal(data, &artifact); err != nil {
		t.Fatalf("Unmarshal error: %v", err)
	}
	if artifact.Backend != "git" {
		t.Errorf("backend = %q, want git", artifact.Backend)
	}
	if artifact.Path != "README.md" {
		t.Errorf("path = %q, want README.md", artifact.Path)
	}
	if artifact.Key == "" {
		t.Error("key should not be empty")
	}
}

func TestGenerateGitArtifactsResume(t *testing.T) {
	dir := t.TempDir()

	run := func(args ...string) {
		t.Helper()
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "HOME="+dir)
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("command %v failed: %v\n%s", args, err, out)
		}
	}

	run("git", "init")
	run("git", "config", "user.email", "test@test.com")
	run("git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(dir, "a.txt"), []byte("aaa\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "b.txt"), []byte("bbb\n"), 0o644)
	run("git", "add", ".")
	run("git", "commit", "-m", "init")

	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	filesDir := filepath.Join(dir, "output", "files")
	blobInfoMap, _ := buildBlobInfoMap(nil)
	pathCommits := map[string][]string{"a.txt": {"h1"}, "b.txt": {"h1"}}
	commitMap := map[string]Commit{"h1": {Hash: "h1"}}

	// First run — generates both
	count, _, err := generateGitArtifacts(filesDir, "head", "url", Preset{}, pathCommits, commitMap, blobInfoMap, false, nil, false, map[string]bool{}, map[string]bool{}, nil)
	if err != nil {
		t.Fatalf("first run error: %v", err)
	}
	if count != 2 {
		t.Fatalf("first run: expected 2, got %d", count)
	}

	// Second run with resume — should skip both
	count, _, err = generateGitArtifacts(filesDir, "head", "url", Preset{}, pathCommits, commitMap, blobInfoMap, false, nil, true, map[string]bool{}, map[string]bool{}, nil)
	if err != nil {
		t.Fatalf("resume run error: %v", err)
	}
	if count != 0 {
		t.Errorf("resume run: expected 0 (all skipped), got %d", count)
	}
}

func TestParseMarkdown(t *testing.T) {
	t.Run("title and sections", func(t *testing.T) {
		source := []byte("# My Dataset\n\n## Installation\n\nSome text.\n\n### Usage\n\nMore text.\n")
		title, sections, content, metadata := parseMarkdown(source)
		if title != "My Dataset" {
			t.Errorf("title = %q, want %q", title, "My Dataset")
		}
		if len(sections) != 3 {
			t.Fatalf("expected 3 sections, got %d", len(sections))
		}
		if sections[0].Level != 1 || sections[0].Text != "My Dataset" {
			t.Errorf("sections[0] = %+v", sections[0])
		}
		if sections[1].Level != 2 || sections[1].Text != "Installation" {
			t.Errorf("sections[1] = %+v", sections[1])
		}
		if sections[2].Level != 3 || sections[2].Text != "Usage" {
			t.Errorf("sections[2] = %+v", sections[2])
		}
		if content == "" {
			t.Error("content should not be empty")
		}
		if len(metadata) != 0 {
			t.Errorf("metadata should be empty, got %v", metadata)
		}
	})

	t.Run("no headings", func(t *testing.T) {
		source := []byte("Just some plain text without any headings.\n")
		title, sections, content, _ := parseMarkdown(source)
		if title != "" {
			t.Errorf("title = %q, want empty", title)
		}
		if len(sections) != 0 {
			t.Errorf("expected 0 sections, got %d", len(sections))
		}
		if content == "" {
			t.Error("content should not be empty")
		}
	})

	t.Run("front matter populates metadata", func(t *testing.T) {
		source := []byte("---\ntag:\n  - rnaseq\n  - bulk\nspecies: human\n---\n# My Dataset\n\nContent here.\n")
		title, _, content, metadata := parseMarkdown(source)
		if title != "My Dataset" {
			t.Errorf("title = %q, want %q", title, "My Dataset")
		}
		tags, ok := metadata["tag"]
		if !ok || len(tags) != 2 || tags[0] != "rnaseq" || tags[1] != "bulk" {
			t.Errorf("metadata[tag] = %v, want [rnaseq bulk]", tags)
		}
		species, ok := metadata["species"]
		if !ok || len(species) != 1 || species[0] != "human" {
			t.Errorf("metadata[species] = %v, want [human]", species)
		}
		// Front matter should be stripped from content
		if strings.Contains(content, "---") {
			t.Error("content should not contain front matter delimiters")
		}
		if !strings.Contains(content, "# My Dataset") {
			t.Error("content should contain the markdown body")
		}
	})

	t.Run("no front matter", func(t *testing.T) {
		source := []byte("# Title\n\nBody text.\n")
		_, _, _, metadata := parseMarkdown(source)
		if len(metadata) != 0 {
			t.Errorf("metadata should be empty, got %v", metadata)
		}
	})
}

func TestIsReadme(t *testing.T) {
	tests := []struct {
		path string
		want bool
	}{
		{"README.md", true},
		{"readme.md", true},
		{"README.MD", true},
		{"README", true},
		{"readme", true},
		{"docs/README.md", true},
		{"src.go", false},
		{"READMEX.md", false},
		{"guide.md", false},
	}
	for _, tt := range tests {
		if got := isReadme(tt.path); got != tt.want {
			t.Errorf("isReadme(%q) = %v, want %v", tt.path, got, tt.want)
		}
	}
}

func TestIsMarkdownFile(t *testing.T) {
	tests := []struct {
		path string
		want bool
	}{
		{"README.md", true},
		{"docs/guide.MD", true},
		{"CHANGELOG.md", true},
		{"src.go", false},
		{"data.csv", false},
		{"readme", false},
	}
	for _, tt := range tests {
		if got := isMarkdownFile(tt.path); got != tt.want {
			t.Errorf("isMarkdownFile(%q) = %v, want %v", tt.path, got, tt.want)
		}
	}
}

func TestGenerateMarkdownArtifacts(t *testing.T) {
	dir := t.TempDir()

	run := func(args ...string) {
		t.Helper()
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "HOME="+dir)
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("command %v failed: %v\n%s", args, err, out)
		}
	}

	run("git", "init")
	run("git", "config", "user.email", "test@test.com")
	run("git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(dir, "README.md"), []byte("---\ntag:\n  - data\n---\n# My Project\n\n## Overview\n\nSome text.\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "src.go"), []byte("package main\n"), 0o644)
	os.MkdirAll(filepath.Join(dir, "docs"), 0o755)
	os.WriteFile(filepath.Join(dir, "docs", "guide.md"), []byte("# Guide\n\nInstructions.\n"), 0o644)
	run("git", "add", ".")
	run("git", "commit", "-m", "init")

	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	blobInfoMap, err := buildBlobInfoMap(nil)
	if err != nil {
		t.Fatalf("buildBlobInfoMap error: %v", err)
	}
	pathCommits := map[string][]string{
		"README.md":     {"aaaa"},
		"src.go":        {"aaaa"},
		"docs/guide.md": {"aaaa"},
	}
	commitMap := map[string]Commit{
		"aaaa": {Hash: "aaaa", Subject: "init"},
	}

	t.Run("root only by default", func(t *testing.T) {
		outDir := filepath.Join(dir, "out-root", "files")
		count, _, mdFiles, err := generateMarkdownArtifacts(outDir, "headhash", "https://example.com/repo.git", Preset{}, pathCommits, commitMap, blobInfoMap, false, nil, false, map[string]bool{}, nil)
		if err != nil {
			t.Fatalf("error: %v", err)
		}
		if count != 1 {
			t.Errorf("expected 1 markdown artifact (root only), got %d", count)
		}
		if !mdFiles["README.md"] {
			t.Error("README.md should be in markdownFiles set")
		}
		if mdFiles["docs/guide.md"] {
			t.Error("docs/guide.md should NOT be in markdownFiles set without --markdown-recursive")
		}

		// Verify the markdown artifact JSON
		data, err := os.ReadFile(filepath.Join(outDir, "README.md.json"))
		if err != nil {
			t.Fatalf("ReadFile error: %v", err)
		}
		var artifact MarkdownArtifact
		if err := json.Unmarshal(data, &artifact); err != nil {
			t.Fatalf("Unmarshal error: %v", err)
		}
		if artifact.Schema != "exohub-markdown/v1.json" {
			t.Errorf("schema = %q, want exohub-markdown/v1.json", artifact.Schema)
		}
		if !artifact.IsReadme {
			t.Error("is_readme should be true for README.md")
		}
		if artifact.Title != "My Project" {
			t.Errorf("title = %q, want %q", artifact.Title, "My Project")
		}
		if len(artifact.Sections) != 2 {
			t.Errorf("expected 2 sections, got %d", len(artifact.Sections))
		}
		if artifact.Backend != "git" {
			t.Errorf("backend = %q, want git", artifact.Backend)
		}
		tags, ok := artifact.Metadata["tag"]
		if !ok || len(tags) != 1 || tags[0] != "data" {
			t.Errorf("metadata[tag] = %v, want [data]", tags)
		}
	})

	t.Run("recursive processes subdirectories", func(t *testing.T) {
		outDir := filepath.Join(dir, "out-recursive", "files")
		count, _, mdFiles, err := generateMarkdownArtifacts(outDir, "headhash", "https://example.com/repo.git", Preset{MarkdownRecursive: true}, pathCommits, commitMap, blobInfoMap, false, nil, false, map[string]bool{}, nil)
		if err != nil {
			t.Fatalf("error: %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2 markdown artifacts (recursive), got %d", count)
		}
		if !mdFiles["README.md"] || !mdFiles["docs/guide.md"] {
			t.Errorf("markdownFiles should contain both files, got %v", mdFiles)
		}

		// Verify nested file is not a readme
		data, err := os.ReadFile(filepath.Join(outDir, "docs", "guide.md.json"))
		if err != nil {
			t.Fatalf("ReadFile error: %v", err)
		}
		var artifact MarkdownArtifact
		if err := json.Unmarshal(data, &artifact); err != nil {
			t.Fatalf("Unmarshal error: %v", err)
		}
		if artifact.IsReadme {
			t.Error("is_readme should be false for docs/guide.md")
		}
	})

	t.Run("git artifacts exclude markdown files", func(t *testing.T) {
		// Generate markdown artifacts first
		mdDir := filepath.Join(dir, "out-exclusion", "files")
		_, _, mdFiles, err := generateMarkdownArtifacts(mdDir, "headhash", "url", Preset{}, pathCommits, commitMap, blobInfoMap, false, nil, false, map[string]bool{}, nil)
		if err != nil {
			t.Fatalf("markdown error: %v", err)
		}

		// Now generate git artifacts — README.md should be excluded
		gitDir := filepath.Join(dir, "out-exclusion-git", "files")
		count, _, err := generateGitArtifacts(gitDir, "headhash", "url", Preset{}, pathCommits, commitMap, blobInfoMap, false, nil, false, map[string]bool{}, mdFiles, nil)
		if err != nil {
			t.Fatalf("git artifacts error: %v", err)
		}
		// Should have src.go + docs/guide.md (guide.md not in mdFiles since non-recursive)
		if count != 2 {
			t.Errorf("expected 2 git artifacts (src.go + docs/guide.md), got %d", count)
		}
		// README.md.json should NOT exist in git output
		if _, err := os.Stat(filepath.Join(gitDir, "README.md.json")); err == nil {
			t.Error("README.md.json should not exist in git artifacts output (handled by markdown)")
		}
	})
}

func TestMarkdownUnderAnnexScope(t *testing.T) {
	dir := t.TempDir()

	run := func(args ...string) {
		t.Helper()
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "HOME="+dir)
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("command %v failed: %v\n%s", args, err, out)
		}
	}

	run("git", "init")
	run("git", "config", "user.email", "test@test.com")
	run("git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(dir, "README.md"), []byte("# Title\n\nSome text.\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "data.csv"), []byte("a,b\n1,2\n"), 0o644)
	os.MkdirAll(filepath.Join(dir, "docs"), 0o755)
	os.WriteFile(filepath.Join(dir, "docs", "guide.md"), []byte("# Guide\n\nInstructions.\n"), 0o644)
	run("git", "add", ".")
	run("git", "commit", "-m", "init")

	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	blobInfoMap, err := buildBlobInfoMap(nil)
	if err != nil {
		t.Fatalf("buildBlobInfoMap error: %v", err)
	}
	pathCommits := map[string][]string{
		"README.md":     {"aaaa"},
		"data.csv":      {"aaaa"},
		"docs/guide.md": {"aaaa"},
	}
	commitMap := map[string]Commit{
		"aaaa": {Hash: "aaaa", Subject: "init"},
	}

	t.Run("annex scope produces markdown artifact", func(t *testing.T) {
		outDir := filepath.Join(dir, "out-annex", "files")
		count, _, mdFiles, err := generateMarkdownArtifacts(outDir, "headhash", "https://example.com/repo.git", Preset{}, pathCommits, commitMap, blobInfoMap, false, nil, false, map[string]bool{}, nil)
		if err != nil {
			t.Fatalf("error: %v", err)
		}
		if count != 1 {
			t.Errorf("expected markdown_file_count == 1, got %d", count)
		}
		if !mdFiles["README.md"] {
			t.Error("README.md should be in markdownFiles set")
		}
		data, err := os.ReadFile(filepath.Join(outDir, "README.md.json"))
		if err != nil {
			t.Fatalf("ReadFile error: %v", err)
		}
		var artifact MarkdownArtifact
		if err := json.Unmarshal(data, &artifact); err != nil {
			t.Fatalf("Unmarshal error: %v", err)
		}
		if artifact.Schema != "exohub-markdown/v1.json" {
			t.Errorf("schema = %q, want exohub-markdown/v1.json", artifact.Schema)
		}
	})

	t.Run("annex scope with recursive includes subdirs", func(t *testing.T) {
		outDir := filepath.Join(dir, "out-annex-recursive", "files")
		count, _, mdFiles, err := generateMarkdownArtifacts(outDir, "headhash", "https://example.com/repo.git", Preset{MarkdownRecursive: true}, pathCommits, commitMap, blobInfoMap, false, nil, false, map[string]bool{}, nil)
		if err != nil {
			t.Fatalf("error: %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2 markdown artifacts, got %d", count)
		}
		if !mdFiles["README.md"] || !mdFiles["docs/guide.md"] {
			t.Errorf("markdownFiles should contain both files, got %v", mdFiles)
		}
	})

	t.Run("annex scope with no markdown yields count 0", func(t *testing.T) {
		noMdDir := t.TempDir()
		runNoMd := func(args ...string) {
			t.Helper()
			cmd := exec.Command(args[0], args[1:]...)
			cmd.Dir = noMdDir
			cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "HOME="+noMdDir)
			out, err := cmd.CombinedOutput()
			if err != nil {
				t.Fatalf("command %v failed: %v\n%s", args, err, out)
			}
		}
		runNoMd("git", "init")
		runNoMd("git", "config", "user.email", "test@test.com")
		runNoMd("git", "config", "user.name", "Test")
		os.WriteFile(filepath.Join(noMdDir, "data.csv"), []byte("a,b\n1,2\n"), 0o644)
		runNoMd("git", "add", ".")
		runNoMd("git", "commit", "-m", "init")

		origDir2, _ := os.Getwd()
		os.Chdir(noMdDir)
		defer os.Chdir(origDir2)

		blobInfoMapNoMd, err := buildBlobInfoMap(nil)
		if err != nil {
			t.Fatalf("buildBlobInfoMap error: %v", err)
		}
		pathCommitsNoMd := map[string][]string{"data.csv": {"bbbb"}}
		commitMapNoMd := map[string]Commit{"bbbb": {Hash: "bbbb", Subject: "init"}}

		outDir := filepath.Join(noMdDir, "out-nomd", "files")
		count, _, _, err := generateMarkdownArtifacts(outDir, "headhash", "https://example.com/repo.git", Preset{}, pathCommitsNoMd, commitMapNoMd, blobInfoMapNoMd, false, nil, false, map[string]bool{}, nil)
		if err != nil {
			t.Fatalf("error: %v", err)
		}
		if count != 0 {
			t.Errorf("expected markdown_file_count == 0, got %d", count)
		}
	})

	t.Run("all scope deduplicates markdown files", func(t *testing.T) {
		mdOutDir := filepath.Join(dir, "out-dedup-md", "files")
		_, _, mdFiles, err := generateMarkdownArtifacts(mdOutDir, "headhash", "https://example.com/repo.git", Preset{}, pathCommits, commitMap, blobInfoMap, false, nil, false, map[string]bool{}, nil)
		if err != nil {
			t.Fatalf("markdown error: %v", err)
		}
		gitOutDir := filepath.Join(dir, "out-dedup-git", "files")
		_, _, err = generateGitArtifacts(gitOutDir, "headhash", "https://example.com/repo.git", Preset{}, pathCommits, commitMap, blobInfoMap, false, nil, false, map[string]bool{}, mdFiles, nil)
		if err != nil {
			t.Fatalf("git error: %v", err)
		}
		if _, err := os.Stat(filepath.Join(gitOutDir, "README.md.json")); err == nil {
			t.Error("README.md.json must not appear in git artifacts output (dedup)")
		}
	})
}

func TestCheckCommitReachabilityNoRemote(t *testing.T) {
	dir := t.TempDir()
	run := func(args ...string) {
		t.Helper()
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "HOME="+dir)
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("command %v failed: %v\n%s", args, err, out)
		}
	}

	run("git", "init")
	run("git", "config", "user.email", "test@test.com")
	run("git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(dir, "file.txt"), []byte("hello\n"), 0o644)
	run("git", "add", ".")
	run("git", "commit", "-m", "init")

	origDir, _ := os.Getwd()
	os.Chdir(dir)
	defer os.Chdir(origDir)

	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = dir
	out, _ := cmd.Output()
	headHash := strings.TrimSpace(string(out))

	result := checkCommitReachability(headHash)
	if result != nil {
		t.Errorf("expected nil for repo without remote, got %+v", result)
	}
}

func TestCheckCommitReachabilityInSync(t *testing.T) {
	originDir := t.TempDir()
	localDir := t.TempDir()
	env := append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "HOME="+localDir)

	runIn := func(dir string, args ...string) {
		t.Helper()
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = dir
		cmd.Env = env
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("command %v in %s failed: %v\n%s", args, dir, err, out)
		}
	}

	runIn(originDir, "git", "init", "--bare")
	runIn(localDir, "git", "clone", originDir, ".")
	runIn(localDir, "git", "config", "user.email", "test@test.com")
	runIn(localDir, "git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(localDir, "file.txt"), []byte("hello\n"), 0o644)
	runIn(localDir, "git", "add", ".")
	runIn(localDir, "git", "commit", "-m", "init")
	runIn(localDir, "git", "push")

	origDir, _ := os.Getwd()
	os.Chdir(localDir)
	defer os.Chdir(origDir)

	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = localDir
	out, _ := cmd.Output()
	headHash := strings.TrimSpace(string(out))

	result := checkCommitReachability(headHash)
	if result != nil {
		t.Errorf("expected nil for in-sync repo, got %+v", result)
	}
}

func TestCheckCommitReachabilityUnpushed(t *testing.T) {
	originDir := t.TempDir()
	localDir := t.TempDir()
	env := append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "HOME="+localDir)

	runIn := func(dir string, args ...string) {
		t.Helper()
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = dir
		cmd.Env = env
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("command %v in %s failed: %v\n%s", args, dir, err, out)
		}
	}

	runIn(originDir, "git", "init", "--bare")
	runIn(localDir, "git", "clone", originDir, ".")
	runIn(localDir, "git", "config", "user.email", "test@test.com")
	runIn(localDir, "git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(localDir, "file.txt"), []byte("hello\n"), 0o644)
	runIn(localDir, "git", "add", ".")
	runIn(localDir, "git", "commit", "-m", "first")
	runIn(localDir, "git", "push")

	// Add unpushed commit
	os.WriteFile(filepath.Join(localDir, "file2.txt"), []byte("new\n"), 0o644)
	runIn(localDir, "git", "add", ".")
	runIn(localDir, "git", "commit", "-m", "unpushed")

	origDir, _ := os.Getwd()
	os.Chdir(localDir)
	defer os.Chdir(origDir)

	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = localDir
	out, _ := cmd.Output()
	headHash := strings.TrimSpace(string(out))

	result := checkCommitReachability(headHash)
	if result == nil {
		t.Fatal("expected non-nil result for unpushed commits")
	}
	if result.Diverged {
		t.Error("expected Diverged=false for unpushed-only")
	}
	if result.LocalOnly != 1 {
		t.Errorf("expected LocalOnly=1, got %d", result.LocalOnly)
	}
	if result.RemoteOnly != 0 {
		t.Errorf("expected RemoteOnly=0, got %d", result.RemoteOnly)
	}
}

func TestCheckCommitReachabilityDiverged(t *testing.T) {
	originDir := t.TempDir()
	local1Dir := t.TempDir()
	local2Dir := t.TempDir()
	env := append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "HOME="+local1Dir)

	runIn := func(dir string, args ...string) {
		t.Helper()
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = dir
		cmd.Env = env
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("command %v in %s failed: %v\n%s", args, dir, err, out)
		}
	}

	// Create bare origin and initial clone
	runIn(originDir, "git", "init", "--bare")
	runIn(local1Dir, "git", "clone", originDir, ".")
	runIn(local1Dir, "git", "config", "user.email", "test@test.com")
	runIn(local1Dir, "git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(local1Dir, "file.txt"), []byte("initial\n"), 0o644)
	runIn(local1Dir, "git", "add", ".")
	runIn(local1Dir, "git", "commit", "-m", "initial")
	runIn(local1Dir, "git", "push")

	// Second clone makes a different commit and force-pushes
	runIn(local2Dir, "git", "clone", originDir, ".")
	runIn(local2Dir, "git", "config", "user.email", "test@test.com")
	runIn(local2Dir, "git", "config", "user.name", "Test")
	os.WriteFile(filepath.Join(local2Dir, "file.txt"), []byte("divergent\n"), 0o644)
	runIn(local2Dir, "git", "add", ".")
	runIn(local2Dir, "git", "commit", "-m", "divergent change")
	runIn(local2Dir, "git", "push", "--force")

	// Back in local1: add a local commit (now diverged from origin)
	os.WriteFile(filepath.Join(local1Dir, "other.txt"), []byte("local\n"), 0o644)
	runIn(local1Dir, "git", "add", ".")
	runIn(local1Dir, "git", "commit", "-m", "local change")
	runIn(local1Dir, "git", "fetch")

	origDir, _ := os.Getwd()
	os.Chdir(local1Dir)
	defer os.Chdir(origDir)

	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = local1Dir
	out, _ := cmd.Output()
	headHash := strings.TrimSpace(string(out))

	result := checkCommitReachability(headHash)
	if result == nil {
		t.Fatal("expected non-nil result for diverged repo")
	}
	if !result.Diverged {
		t.Error("expected Diverged=true")
	}
	if result.LocalOnly != 1 {
		t.Errorf("expected LocalOnly=1, got %d", result.LocalOnly)
	}
	if result.RemoteOnly != 1 {
		t.Errorf("expected RemoteOnly=1, got %d", result.RemoteOnly)
	}
}
